server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: login-route
          uri: ${airguardnet.services.user.base-url}
          predicates:
            - Path=/api/login
          filters:
            - SetPath=/auth/login
        - id: register-route
          uri: ${airguardnet.services.user.base-url}
          predicates:
            - Path=/api/register
          filters:
            - SetPath=/auth/register
        - id: user-service
          uri: ${airguardnet.services.user.base-url}
          predicates:
            - Path=/api/auth/**,/api/users/**,/api/access-logs/**,/api/system-logs/**,/api/config-parameters/**,/api/config-change-logs/**,/api/version-history/**,/api/plans/**
          filters:
            - StripPrefix=1
        - id: device-service
          uri: ${airguardnet.services.device.base-url}
          predicates:
            - Path=/api/devices/**,/api/readings/**,/api/alerts/**,/api/usage-reports/**,/api/sensor-configs/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: ${airguardnet.services.notification.base-url}
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1

airguardnet:
  services:
    user:
      base-url: http://localhost:8081
    device:
      base-url: http://localhost:8082
    notification:
      base-url: http://localhost:8083

logging:
  level:
    root: INFO
    com.airguardnet: DEBUG
