server:
  port: 8080

spring:
  application:
    name: api-gateway

airguardnet:
  services:
    user:
      base-url: http://localhost:8081
    device:
      base-url: http://localhost:8082
    notification:
      base-url: http://localhost:8083

jwt:
  secret: "changeitsecret12345678901234567890"
  expiration-ms: 3600000

logging:
  level:
    root: INFO
    com.airguardnet: DEBUG
